# Generated by Django 5.2.6 on 2025-09-08 18:57

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the expenditure record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category of the expenditure (e.g., transport, food, entertainment)",
                        max_length=60,
                    ),
                ),
                (
                    "name_of_item",
                    models.CharField(
                        help_text="Name or description of the item/service",
                        max_length=120,
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated expenditure amount (must be positive)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the expenditure record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the expenditure record was last updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this expenditure record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenditures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expenditure",
                "verbose_name_plural": "Expenditures",
                "db_table": "finance_expenditure",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="finance_exp_user_id_532701_idx",
                    ),
                    models.Index(
                        fields=["category"], name="finance_exp_categor_3a346c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="finance_exp_created_2bf7ad_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the income record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_of_revenue",
                    models.CharField(
                        help_text="Name or description of the revenue source",
                        max_length=120,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Income amount (must be positive)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the income record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the income record was last updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this income record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
                "db_table": "finance_income",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="finance_inc_user_id_ad008f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="finance_inc_created_f04fc1_idx"
                    ),
                ],
            },
        ),
    ]
